import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "hi" | "te";

const translations = {
  en: {
    // Navbar
    findWorkers: "Find Workers",
    jobBoard: "Job Board",
    register: "Register",
    dashboard: "Dashboard",

    // Footer
    madeWith: "Made with",
    forRuralIndia: "for Rural India",

    // Index / Hero
    heroTag: "🌾 Empowering Rural India",
    heroTitle: "Connecting Rural Skills with Real Opportunities",
    heroDesc: "GramSetu bridges the gap between skilled rural artisans and employers, NGOs & government programs seeking their talent.",
    registerAsWorker: "Register as Worker",
    findWorkersBtn: "Find Workers",
    skilledWorkers: "Skilled Workers",
    jobsPosted: "Jobs Posted",
    villagesConnected: "Villages Connected",
    skillsMapped: "Skills Mapped",
    skillsWeMap: "Skills We Map",
    skillsWeMapDesc: "Discover talent across diverse rural skill categories",
    featuredWorkers: "Featured Workers",
    featuredWorkersDesc: "Skilled artisans ready for opportunities",
    viewAll: "View All",
    recentOpportunities: "Recent Opportunities",
    recentOpportunitiesDesc: "Latest jobs and training programs",
    readyToBridge: "Ready to Bridge the Gap?",
    readyToBridgeDesc: "Whether you're a skilled worker seeking opportunities or an employer looking for talent, GramSetu is your bridge to a better future.",
    getStarted: "Get Started",

    // Workers page
    findSkilledWorkers: "Find Skilled Workers",
    findSkilledWorkersDesc: "Search and connect with rural artisans and service providers",
    filters: "Filters",
    searchByNameOrSkill: "Search by name or skill...",
    skillCategory: "Skill Category",
    district: "District",
    availability: "Availability",
    clearAllFilters: "Clear all filters",
    workersFound: "workers found",
    workerFound: "worker found",
    experience: "Experience",
    noWorkersFound: "No workers found",
    tryAdjustingFilters: "Try adjusting your filters",
    available: "Available",
    busy: "Busy",
    notAvailable: "Not Available",

    // Jobs page
    jobTrainingBoard: "Job & Training Board",
    jobTrainingBoardDesc: "Browse opportunities from employers, NGOs, and government programs",
    searchJobs: "Search jobs...",
    requiredSkill: "Required Skill",
    location: "Location",
    status: "Status",
    open: "Open",
    closed: "Closed",
    opportunitiesFound: "opportunities found",
    opportunityFound: "opportunity found",
    noOpportunitiesFound: "No opportunities found",
    posted: "Posted",

    // Register page
    registerTitle: "Register",
    registerDesc: "Create your profile to get started on GramSetu",
    worker: "Worker",
    employerNgo: "Employer / NGO",
    workerProfile: "Worker Profile",
    fullName: "Full Name",
    phone: "Phone",
    village: "Village",
    selectDistrict: "Select district",
    experienceLevel: "Experience Level",
    selectLevel: "Select level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    expert: "Expert",
    selectStatus: "Select status",
    skills: "Skills",
    addSkill: "Add Skill",
    skill: "Skill",
    selectSkillCategory: "Select skill category",
    describeWork: "Describe your work and experience...",
    registerAsWorkerBtn: "Register as Worker",
    employerProfile: "Employer / Organization Profile",
    contactName: "Contact Name",
    organizationName: "Organization Name",
    type: "Type",
    selectType: "Select type",
    employer: "Employer",
    ngo: "NGO",
    government: "Government",
    registerAsEmployer: "Register as Employer",
    registrationSuccessful: "Registration Successful!",
    workerSuccessDesc: "Your worker profile has been created. Employers can now discover you.",
    employerSuccessDesc: "Your employer profile has been created. You can now search for workers and post jobs.",
    registerAnother: "Register Another",
    goToDashboard: "Go to Dashboard",
    pleaseFillAllFields: "Please fill all required fields",
    workerRegistered: "Worker profile registered successfully!",
    employerRegistered: "Employer profile registered successfully!",

    // Dashboard
    dashboardTitle: "Dashboard",
    dashboardDesc: "Manage profiles and opportunities",
    postJob: "Post Job",
    postNewOpportunity: "Post a New Opportunity",
    title: "Title",
    description: "Description",
    contactInfo: "Contact Info",
    postOpportunity: "Post Opportunity",
    workers: "Workers",
    opportunities: "Opportunities",
    jobPosted: "Job posted successfully!",
    pleaseFillAll: "Please fill all fields",
  },
  hi: {
    findWorkers: "कारीगर खोजें",
    jobBoard: "नौकरी बोर्ड",
    register: "पंजीकरण",
    dashboard: "डैशबोर्ड",
    madeWith: "बनाया गया",
    forRuralIndia: "ग्रामीण भारत के लिए",
    heroTag: "🌾 ग्रामीण भारत को सशक्त बनाना",
    heroTitle: "ग्रामीण कौशल को वास्तविक अवसरों से जोड़ना",
    heroDesc: "ग्रामसेतु कुशल ग्रामीण कारीगरों और नियोक्ताओं, NGO तथा सरकारी कार्यक्रमों के बीच की दूरी को पाटता है।",
    registerAsWorker: "कारीगर के रूप में पंजीकरण करें",
    findWorkersBtn: "कारीगर खोजें",
    skilledWorkers: "कुशल कारीगर",
    jobsPosted: "नौकरियाँ पोस्ट की गईं",
    villagesConnected: "गाँव जुड़े",
    skillsMapped: "कौशल मैप किए गए",
    skillsWeMap: "हम जो कौशल मैप करते हैं",
    skillsWeMapDesc: "विविध ग्रामीण कौशल श्रेणियों में प्रतिभा खोजें",
    featuredWorkers: "प्रमुख कारीगर",
    featuredWorkersDesc: "अवसरों के लिए तैयार कुशल कारीगर",
    viewAll: "सभी देखें",
    recentOpportunities: "हाल के अवसर",
    recentOpportunitiesDesc: "नवीनतम नौकरियाँ और प्रशिक्षण कार्यक्रम",
    readyToBridge: "अंतर पाटने के लिए तैयार हैं?",
    readyToBridgeDesc: "चाहे आप अवसर खोज रहे कुशल कारीगर हों या प्रतिभा खोज रहे नियोक्ता, ग्रामसेतु बेहतर भविष्य का सेतु है।",
    getStarted: "शुरू करें",
    findSkilledWorkers: "कुशल कारीगर खोजें",
    findSkilledWorkersDesc: "ग्रामीण कारीगरों और सेवा प्रदाताओं से खोजें और जुड़ें",
    filters: "फ़िल्टर",
    searchByNameOrSkill: "नाम या कौशल से खोजें...",
    skillCategory: "कौशल श्रेणी",
    district: "जिला",
    availability: "उपलब्धता",
    clearAllFilters: "सभी फ़िल्टर हटाएं",
    workersFound: "कारीगर मिले",
    workerFound: "कारीगर मिला",
    experience: "अनुभव",
    noWorkersFound: "कोई कारीगर नहीं मिला",
    tryAdjustingFilters: "अपने फ़िल्टर बदलकर देखें",
    available: "उपलब्ध",
    busy: "व्यस्त",
    notAvailable: "उपलब्ध नहीं",
    jobTrainingBoard: "नौकरी और प्रशिक्षण बोर्ड",
    jobTrainingBoardDesc: "नियोक्ताओं, NGO और सरकारी कार्यक्रमों के अवसर देखें",
    searchJobs: "नौकरियाँ खोजें...",
    requiredSkill: "आवश्यक कौशल",
    location: "स्थान",
    status: "स्थिति",
    open: "खुला",
    closed: "बंद",
    opportunitiesFound: "अवसर मिले",
    opportunityFound: "अवसर मिला",
    noOpportunitiesFound: "कोई अवसर नहीं मिला",
    posted: "पोस्ट किया",
    registerTitle: "पंजीकरण",
    registerDesc: "GramSetu पर शुरू करने के लिए अपनी प्रोफाइल बनाएं",
    worker: "कारीगर",
    employerNgo: "नियोक्ता / NGO",
    workerProfile: "कारीगर प्रोफाइल",
    fullName: "पूरा नाम",
    phone: "फ़ोन",
    village: "गाँव",
    selectDistrict: "जिला चुनें",
    experienceLevel: "अनुभव स्तर",
    selectLevel: "स्तर चुनें",
    beginner: "शुरुआती",
    intermediate: "मध्यवर्ती",
    expert: "विशेषज्ञ",
    selectStatus: "स्थिति चुनें",
    skills: "कौशल",
    addSkill: "कौशल जोड़ें",
    skill: "कौशल",
    selectSkillCategory: "कौशल श्रेणी चुनें",
    describeWork: "अपने काम और अनुभव का वर्णन करें...",
    registerAsWorkerBtn: "कारीगर के रूप में पंजीकरण करें",
    employerProfile: "नियोक्ता / संगठन प्रोफाइल",
    contactName: "संपर्क नाम",
    organizationName: "संगठन का नाम",
    type: "प्रकार",
    selectType: "प्रकार चुनें",
    employer: "नियोक्ता",
    ngo: "NGO",
    government: "सरकार",
    registerAsEmployer: "नियोक्ता के रूप में पंजीकरण करें",
    registrationSuccessful: "पंजीकरण सफल!",
    workerSuccessDesc: "आपकी कारीगर प्रोफाइल बन गई है। नियोक्ता अब आपको खोज सकते हैं।",
    employerSuccessDesc: "आपकी नियोक्ता प्रोफाइल बन गई है। अब आप कारीगरों को खोज सकते हैं और नौकरियाँ पोस्ट कर सकते हैं।",
    registerAnother: "और पंजीकरण करें",
    goToDashboard: "डैशबोर्ड पर जाएं",
    pleaseFillAllFields: "कृपया सभी आवश्यक फ़ील्ड भरें",
    workerRegistered: "कारीगर प्रोफाइल सफलतापूर्वक पंजीकृत!",
    employerRegistered: "नियोक्ता प्रोफाइल सफलतापूर्वक पंजीकृत!",
    dashboardTitle: "डैशबोर्ड",
    dashboardDesc: "प्रोफाइल और अवसर प्रबंधित करें",
    postJob: "नौकरी पोस्ट करें",
    postNewOpportunity: "नया अवसर पोस्ट करें",
    title: "शीर्षक",
    description: "विवरण",
    contactInfo: "संपर्क जानकारी",
    postOpportunity: "अवसर पोस्ट करें",
    workers: "कारीगर",
    opportunities: "अवसर",
    jobPosted: "नौकरी सफलतापूर्वक पोस्ट की गई!",
    pleaseFillAll: "कृपया सभी फ़ील्ड भरें",
  },
  te: {
    findWorkers: "కార్మికులను కనుగొనండి",
    jobBoard: "ఉద్యోగ బోర్డు",
    register: "నమోదు",
    dashboard: "డాష్‌బోర్డ్",
    madeWith: "తయారు చేయబడింది",
    forRuralIndia: "గ్రామీణ భారతదేశం కోసం",
    heroTag: "🌾 గ్రామీణ భారతదేశాన్ని సాధికారం చేయడం",
    heroTitle: "గ్రామీణ నైపుణ్యాలను నిజమైన అవకాశాలతో అనుసంధానం",
    heroDesc: "గ్రామసేతు నైపుణ్యం కలిగిన గ్రామీణ కళాకారులు మరియు యజమానులు, NGOలు & ప్రభుత్వ కార్యక్రమాల మధ్య అంతరాన్ని తగ్గిస్తుంది.",
    registerAsWorker: "కార్మికుడిగా నమోదు చేయండి",
    findWorkersBtn: "కార్మికులను కనుగొనండి",
    skilledWorkers: "నైపుణ్యం కలిగిన కార్మికులు",
    jobsPosted: "పోస్ట్ చేసిన ఉద్యోగాలు",
    villagesConnected: "అనుసంధానమైన గ్రామాలు",
    skillsMapped: "మ్యాప్ చేసిన నైపుణ్యాలు",
    skillsWeMap: "మేము మ్యాప్ చేసే నైపుణ్యాలు",
    skillsWeMapDesc: "వివిధ గ్రామీణ నైపుణ్య వర్గాలలో ప్రతిభను కనుగొనండి",
    featuredWorkers: "ప్రముఖ కార్మికులు",
    featuredWorkersDesc: "అవకాశాలకు సిద్ధంగా ఉన్న నైపుణ్యం కలిగిన కళాకారులు",
    viewAll: "అన్నీ చూడండి",
    recentOpportunities: "ఇటీవలి అవకాశాలు",
    recentOpportunitiesDesc: "తాజా ఉద్యోగాలు మరియు శిక్షణ కార్యక్రమాలు",
    readyToBridge: "అంతరాన్ని తగ్గించడానికి సిద్ధంగా ఉన్నారా?",
    readyToBridgeDesc: "మీరు అవకాశాలు వెతుకుతున్న నైపుణ్యం కలిగిన కార్మికుడైనా లేదా ప్రతిభను వెతుకుతున్న యజమానైనా, గ్రామసేతు మెరుగైన భవిష్యత్తుకు వారధి.",
    getStarted: "ప్రారంభించండి",
    findSkilledWorkers: "నైపుణ్యం కలిగిన కార్మికులను కనుగొనండి",
    findSkilledWorkersDesc: "గ్రామీణ కళాకారులు మరియు సేవా ప్రదాతలతో కనుగొని అనుసంధానం అవ్వండి",
    filters: "ఫిల్టర్లు",
    searchByNameOrSkill: "పేరు లేదా నైపుణ్యం ద్వారా శోధించండి...",
    skillCategory: "నైపుణ్య వర్గం",
    district: "జిల్లా",
    availability: "అందుబాటు",
    clearAllFilters: "అన్ని ఫిల్టర్లు తొలగించండి",
    workersFound: "కార్మికులు కనుగొనబడ్డారు",
    workerFound: "కార్మికుడు కనుగొనబడ్డాడు",
    experience: "అనుభవం",
    noWorkersFound: "కార్మికులు కనుగొనబడలేదు",
    tryAdjustingFilters: "మీ ఫిల్టర్లను సర్దుబాటు చేయడానికి ప్రయత్నించండి",
    available: "అందుబాటులో",
    busy: "బిజీ",
    notAvailable: "అందుబాటులో లేదు",
    jobTrainingBoard: "ఉద్యోగ & శిక్షణ బోర్డు",
    jobTrainingBoardDesc: "యజమానులు, NGOలు మరియు ప్రభుత్వ కార్యక్రమాల నుండి అవకాశాలను బ్రౌజ్ చేయండి",
    searchJobs: "ఉద్యోగాలు శోధించండి...",
    requiredSkill: "అవసరమైన నైపుణ్యం",
    location: "స్థానం",
    status: "స్థితి",
    open: "తెరిచి ఉంది",
    closed: "మూసివేయబడింది",
    opportunitiesFound: "అవకాశాలు కనుగొనబడ్డాయి",
    opportunityFound: "అవకాశం కనుగొనబడింది",
    noOpportunitiesFound: "అవకాశాలు కనుగొనబడలేదు",
    posted: "పోస్ట్ చేయబడింది",
    registerTitle: "నమోదు",
    registerDesc: "GramSetu లో ప్రారంభించడానికి మీ ప్రొఫైల్ సృష్టించండి",
    worker: "కార్మికుడు",
    employerNgo: "యజమాని / NGO",
    workerProfile: "కార్మికుడి ప్రొఫైల్",
    fullName: "పూర్తి పేరు",
    phone: "ఫోన్",
    village: "గ్రామం",
    selectDistrict: "జిల్లా ఎంచుకోండి",
    experienceLevel: "అనుభవ స్థాయి",
    selectLevel: "స్థాయి ఎంచుకోండి",
    beginner: "ప్రారంభకుడు",
    intermediate: "మధ్యస్థం",
    expert: "నిపుణుడు",
    selectStatus: "స్థితి ఎంచుకోండి",
    skills: "నైపుణ్యాలు",
    addSkill: "నైపుణ్యం జోడించండి",
    skill: "నైపుణ్యం",
    selectSkillCategory: "నైపుణ్య వర్గం ఎంచుకోండి",
    describeWork: "మీ పని మరియు అనుభవాన్ని వివరించండి...",
    registerAsWorkerBtn: "కార్మికుడిగా నమోదు చేయండి",
    employerProfile: "యజమాని / సంస్థ ప్రొఫైల్",
    contactName: "సంప్రదింపు పేరు",
    organizationName: "సంస్థ పేరు",
    type: "రకం",
    selectType: "రకం ఎంచుకోండి",
    employer: "యజమాని",
    ngo: "NGO",
    government: "ప్రభుత్వం",
    registerAsEmployer: "యజమానిగా నమోదు చేయండి",
    registrationSuccessful: "నమోదు విజయవంతం!",
    workerSuccessDesc: "మీ కార్మికుడి ప్రొఫైల్ సృష్టించబడింది. యజమానులు ఇప్పుడు మిమ్మల్ని కనుగొనగలరు.",
    employerSuccessDesc: "మీ యజమాని ప్రొఫైల్ సృష్టించబడింది. మీరు ఇప్పుడు కార్మికులను శోధించి ఉద్యోగాలు పోస్ట్ చేయవచ్చు.",
    registerAnother: "మరొకటి నమోదు చేయండి",
    goToDashboard: "డాష్‌బోర్డ్‌కు వెళ్ళండి",
    pleaseFillAllFields: "దయచేసి అన్ని అవసరమైన ఫీల్డ్‌లను పూరించండి",
    workerRegistered: "కార్మికుడి ప్రొఫైల్ విజయవంతంగా నమోదు చేయబడింది!",
    employerRegistered: "యజమాని ప్రొఫైల్ విజయవంతంగా నమోదు చేయబడింది!",
    dashboardTitle: "డాష్‌బోర్డ్",
    dashboardDesc: "ప్రొఫైల్‌లు మరియు అవకాశాలను నిర్వహించండి",
    postJob: "ఉద్యోగం పోస్ట్ చేయండి",
    postNewOpportunity: "కొత్త అవకాశం పోస్ట్ చేయండి",
    title: "శీర్షిక",
    description: "వివరణ",
    contactInfo: "సంప్రదింపు సమాచారం",
    postOpportunity: "అవకాశం పోస్ట్ చేయండి",
    workers: "కార్మికులు",
    opportunities: "అవకాశాలు",
    jobPosted: "ఉద్యోగం విజయవంతంగా పోస్ట్ చేయబడింది!",
    pleaseFillAll: "దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి",
  },
} as const;

type Translations = Record<keyof typeof translations.en, string>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: translations.en,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");
  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
